### ISSUE TITLE
Implement `{x:Uid ...}`

### ISSUE THREAD

**Issue by Poker-sang** [levitali/CompiledBindings#17]
Is it possible to implement markup extension `{x:Uid ...}` in WPF? Or any alternative to it to achieve?
When meeting the needs of globalization, I feel like that `{x:Uid ...}` works well along with .resw files.

**Comment by levitali** [comment]
You can easily create your own markup extension, by deriving from MarkupExtension class and overriding the ProvideValue method. In the method you can get value from resources.
Note, x:Uid in UWP is not a markup extension. it's a directive. Implementing custom directives in XAML is not possible.
Actually, it has nothing to do with this library, IMO.

**Comment by Poker-sang** [comment]
Thanks
