### ISSUE TITLE
x:Bind string interpolation error

### ISSUE THREAD

**Issue by salk52** [levitali/CompiledBindings#25]
I have this line of code in WPF app

` <TextBox Text="{x:Bind $'String value: {Username}'}" />`

and compiler is throwing error

 error MC3043: Names and Values in a MarkupExtension cannot contain quotes. The MarkupExtension arguments ' $'String value: {Username}' 

I'm using VS 17.5.5 and I don't know whats the problem. Does anyone else has this problem? Am I missing something?

**Comment by levitali** [comment]
You have to use the m: Namespace

```xaml
  xmlns:m="http://compiledbindings.com"
  mc:Ignorable="d m"
  ```
  
  ```xaml
  <TextBox m:Text="{x:Bind $'String value: {Username}'}" />
  ```

Alternatively you can use square brackets instead of curly ones.

  ```xaml
  <TextBox Text="[x:Bind $'String value: {Username}']" />
  ```
  
  The second option I do not have yet in readme.

**Comment by salk52** [comment]
I was missing m: in front of text as I was looking this example from README
`<Label Text="{x:Bind $'Decimal value: {DecimalProp:0.###}, Boolean value: {BooleanProp}, String value: {StringProp.TrimStart('0')}'}" />`
which is missing that m: in front of text :)
