### ISSUE TITLE
Build error in MAUI app when using x:Bind with the Vapolia.MauiGesture library

### ISSUE THREAD

**Issue by tranb3r** [levitali/CompiledBindings#27]
Hi,

In a MAUI app, I've managed to use x:Bind pretty much everywhere I need it.
Except when the binding is for a LongPressCommand (from the https://github.com/vapolia/MauiGestures lib).

Here is a link to a simple repro project: [repro](https://github.com/tranb3r/Issues/tree/main/MauiAppTestCompiledBindings)

Here is the code that triggers a build error:
```
<?xml version="1.0" encoding="utf-8" ?>
<Button
    x:Class="MauiAppTestCompiledBindings.MyButton"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiAppTestCompiledBindings"
    xmlns:mauiGestures="clr-namespace:MauiGestures;assembly=MauiGestures"
    mauiGestures:Gesture.LongPressCommand="{x:Bind ClickCommand}"
    x:DataType="local:MainViewModel"
    Text="Click me" />
```

Here is the build error message:
```
error CS1503: Argument 1: cannot convert from 'MauiAppTestCompiledBindings.MyButton.MyButton_Bindings_this' to 'Microsoft.Maui.Controls.BindableObject'
```

Could you please take a look and tell me if you think this is something that can be fixed, either in my code, or in the CompiledBindings library, or in the MauiGesture library?

Thank you!

**Comment by levitali** [comment]
Unfortunately, it’s a bug.

I’ve uploaded a new Version of the MAUI nuget. So far as beta. The problem should be solved.

You should restart Visual Studio after upgrading the nuget. At least on my computer still the old version is used.

Thank you for reporting the issue!

**Comment by tranb3r** [comment]
Wow! That was fast...
Thanks a lot :)
