### ISSUE TITLE
Index was outside the bounds of the array [MAUI]

### ISSUE THREAD

**Issue by Alex-Dobrynin** [levitali/CompiledBindings#31]
when adding this package to .net maui net7 project getting error mentioned in the title
![image](https://github.com/levitali/CompiledBindings/assets/23138430/3bff8f20-e6ae-41ce-a90c-7a6d74745d98)
![image](https://github.com/levitali/CompiledBindings/assets/23138430/2fb1047f-b29f-4ea6-a8df-d3dfe7dd7392)

**Comment by levitali** [comment]
Could you provide a sample with the problem?

**Comment by levitali** [comment]
Sorry, I can't reproduce the issue. It works for me when I create a new project, as well as in all my other maui .net7 projects.
