### ISSUE TITLE
Converter not found, when declared outside the page.

### ISSUE THREAD

**Issue by Petrarca181** [levitali/CompiledBindings#32]
Hi, my converter is declared inside merged dictionary in app.xaml.  So it is accessible globaly  from every page. 

Whe I try to use it with  x:Bind I get:

```
 <myControls:MyEntry
     x:Name="Diaria"
     Title="DIARIA"
     Grid.Row="7"
     Keyboard="Numeric"
     ReturnType="Done"
     Text="{x:Bind Path=Loader.Result.Diaria, Mode=TwoWay, Converter={StaticResource DoubleToStringConverter}}" />
```
 
`System.Collections.Generic.KeyNotFoundException: 'The resource 'DoubleToStringConverter' is not present in the dictionary.'`

till I don't add it directly to the page. 

```
 <ContentPage.Resources>
     <converters:DoubleToStringConverter  x:Key="DoubleToStringConverter"/>
 </ContentPage.Resources>

```

With normal Binding all works fine.  MAUI .NET 7

**Comment by levitali** [comment]
Thank you for reporting the bug. It will be fixed in next version.

**Comment by levitali** [comment]
Should be fixed now.
