### ISSUE TITLE
Syntax error when using x:bind

### ISSUE THREAD

**Issue by BeepBeepBopBop** [levitali/CompiledBindings#35]
Hello, I am trying to use the library but I get a syntax error when trying the following basic expression:

<Label Text="Text" IsVisible="{x:Bind IntValue not 0}"/>

This won't compile. I don't understand if I have to do something in particular after installing the package, I included the "         xmlns:mx="http://compiledbindings.com/x" namespace but not sure if there is something else to do.

Thanks in advance for your help

**Comment by levitali** [comment]
Hello. Could provide the expression?
