### ISSUE TITLE
[MAUI] The "XamlCTask" task failed unexpectedly.

### ISSUE THREAD

**Issue by Alex-Dobrynin** [levitali/CompiledBindings#37]
If i have datatemplate and the root of it is customview like local:SomeCustomRootViewOfTheDataTemplate and if i have there some bindings using x:Bind i get next error during the build. If i change x:Bind to Binding it just successfully builds the app.

![image](https://github.com/levitali/CompiledBindings/assets/23138430/8e515f7d-e50e-4fff-8950-70903992d81c)

Repro:
[DataTemplateWithCustomRootView.zip](https://github.com/levitali/CompiledBindings/files/15024222/DataTemplateWithCustomRootView.zip)

This is really critical as cannot be workarounded

created the same issue in MAUI github
https://github.com/dotnet/maui/issues/21910

**Comment by levitali** [comment]
Thanks you for finding the bug! It is fixed in version 1.0.18
